name: CMake Build

on: [push]

env:
  BUILD_TYPE: Release
  LLVM_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout BitsyLLVM
      uses: actions/checkout@v4
      with:
        path: bitsy-llvm

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/bitsy-llvm/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/bitsy-llvm/build
      run: >
        cmake ..
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DCMAKE_C_COMPILER=clang-$LLVM_VERSION
        -DCMAKE_CXX_COMPILER=clang++-$LLVM_VERSION
        -DLLVM_DIR=/usr/lib/llvm-$LLVM_VERSION/cmake/llvm

    - name: Build
      working-directory: ${{github.workspace}}/bitsy-llvm/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Checkout bitsyspec
      uses: actions/checkout@v4
      with:
        repository:  apbendi/bitsyspec
        path: bitsyspec

    - name: Run tests
      working-directory: ${{github.workspace}}/bitsy-llvm
      shell: bash
      run: ./test/run.py
