name: CMake Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout BitsyLLVM
      uses: actions/checkout@v2
      with:
        path: bitsy-llvm

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: ${{runner.temp}}/llvm
        key: llvm-cache

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "12.0.0"
        force-version: true
        ubuntu-version: 20.04
        directory: ${{runner.temp}}/llvm
        cached: ${{steps.cache-llvm.outputs.cache-hit}}

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/bitsy-llvm/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/bitsy-llvm/build
      run: >
        cmake ..
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DCMAKE_C_COMPILER=${{runner.temp}}/llvm/bin/clang
        -DCMAKE_CXX_COMPILER=${{runner.temp}}/llvm/bin/clang++
        -DLLVM_DIR=${{runner.temp}}/llvm/lib/cmake/llvm/

    - name: Build
      working-directory: ${{github.workspace}}/bitsy-llvm/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Checkout bitsyspec
      uses: actions/checkout@v2
      with:
        repository:  apbendi/bitsyspec
        path: bitsyspec

    - name: Run tests
      working-directory: ${{github.workspace}}/bitsy-llvm
      shell: bash
      run: ./test/run.py
